export const INDEXDB_STORAGE_NAME = {
  FIND_TRIP_ORIGIN_SEARCH_LIST: "FIND_TRIP_ORIGIN_SEARCH_LIST",
  FIND_TRIP_DESTINATION_SEARCH_LIST: "FIND_TRIP_DESTINATION_SEARCH_LIST",
  PLAN_RIDE_TRIP_ORIGIN_SEARCH_LIST: "PLAN_RIDE_TRIP_ORIGIN_SEARCH_LIST",
  PLAN_RIDE_TRIP_DESTINATION_SEARCH_LIST:
    "PLAN_RIDE_TRIP_DESTINATION_SEARCH_LIST",
  CHAT_TRIP_ROOM_DETAIL: "CHAT_TRIP_ROOM_DETAIL",
};
