export const ENVIRONMENTS = {
  GOOGLE_MAP_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY ?? "",
  ROUTES_GOOGLE_API_URL: process.env.NEXT_PUBLIC_ROUTES_GOOGLE_API_URL ?? "",
  MAPS_GOOGLE_API_URL: process.env.NEXT_PUBLIC_MAPS_GOOGLE_API_URL ?? "",
  SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "",
  SIMPLY_HOP_API_URL: process.env.NEXT_PUBLIC_SIMPLY_HOP_API_URL ?? "",
};
